// Spec: ISO C 7.12 (the constants its functions are built on), IEEE 754 binary64: the values
// MathConstants.h declares. Generated by tools/math-tables.py; do not edit.

#include "MathConstants.h"

namespace rts6x {

const double MathConstants::halfPiHi = 1.5707963267948966;
const double MathConstants::halfPiLo = 6.123233995736766e-17;
const double MathConstants::piHi = 3.141592653589793;
const double MathConstants::piLo = 1.2246467991473532e-16;
const double MathConstants::twoOverPi = 0.6366197723675814;
const double MathConstants::halfPiPart1 = 1.5707963267341256;
const double MathConstants::halfPiPart2 = 6.077100506303966e-11;
const double MathConstants::halfPiPart3 = 2.0222662487111665e-21;
const double MathConstants::halfPiPart4 = 8.4784276603689e-32;
const double MathConstants::piBy256Part1 = 0.012271846302610356;
const double MathConstants::piBy256Part2 = 4.747734770549973e-13;
const double MathConstants::piBy256Part3 = 1.5798955068055988e-23;
const double MathConstants::piBy256Part4 = 6.623771609663203e-34;
const double MathConstants::twoFiftySixByPi = 81.48733086305042;
const double MathConstants::ln2Hi = 0.6931471805598903;
const double MathConstants::ln2Lo = 5.497923018708371e-14;
const double MathConstants::ln2By64Hi = 0.010830424696223417;
const double MathConstants::ln2By64Lo = 2.572804622327669e-14;
const double MathConstants::sixtyFourByLn2 = 92.33248261689366;
const double MathConstants::invLn10Hi = 0.4342944819032518;
const double MathConstants::invLn10Lo = 1.098319650216765e-17;

}  // namespace rts6x
