// Spec: ISO C 7.12 (the constants its functions are built on), IEEE 754 binary64. Generated by tools/math-tables.py; do not edit.
// pi from Machin's formula, ln 2 and ln 10 from the atanh series, in integers to 700 bits; each
// value the nearest double, or a sum of doubles where one is not enough.
#ifndef RTS6X_MATH_CONSTANTS_H
#define RTS6X_MATH_CONSTANTS_H

namespace rts6x {

// Data members rather than inline functions: cpp11 loads one where it is named in an expression,
// where an inline call there costs a push and a pop of everything evaluated before it.
class MathConstants {
public:
    // pi/2, double-double
    static const double halfPiHi;
    static const double halfPiLo;
    // pi, double-double
    static const double piHi;
    static const double piLo;
    // 2/pi, nearest double: the quadrant guess
    static const double twoOverPi;
    // pi/2 = part1 + part2 + part3 + part4
    static const double halfPiPart1;
    static const double halfPiPart2;
    static const double halfPiPart3;
    static const double halfPiPart4;
    // pi/256 = the four parts of pi/2 over 128, exactly
    static const double piBy256Part1;
    static const double piBy256Part2;
    static const double piBy256Part3;
    static const double piBy256Part4;
    // 256/pi, nearest double: the sine table index guess
    static const double twoFiftySixByPi;
    // ln 2 = ln2Hi + ln2Lo, ln2Hi of 42 bits: e * ln2Hi is exact
    static const double ln2Hi;
    static const double ln2Lo;
    // ln 2 / 64 = hi + lo, hi of 36 bits: n * hi exact for |n| < 2^17
    static const double ln2By64Hi;
    static const double ln2By64Lo;
    // 64 / ln 2, nearest double
    static const double sixtyFourByLn2;
    // ln 2 / 128 = hi + lo, hi of 35 bits: n * hi exact for |n| < 2^18
    static const double ln2By128Hi;
    static const double ln2By128Lo;
    // 128 / ln 2, nearest double
    static const double oneTwentyEightByLn2;
    // 1 / ln 10, double-double
    static const double invLn10Hi;
    static const double invLn10Lo;
};

}  // namespace rts6x

#endif
