// Spec: ISO C 7.12 (the constants its functions are built on), IEEE 754 binary64. Generated by tools/math-tables.py; do not edit.
// pi from Machin's formula, ln 2 and ln 10 from the atanh series, in integers to 700 bits; each
// value the nearest double, or a sum of doubles where one is not enough.
#ifndef RTS6X_MATH_CONSTANTS_H
#define RTS6X_MATH_CONSTANTS_H

namespace rts6x {

class MathConstants {
public:
    // pi/2, double-double
    static double halfPiHi() { return 1.5707963267948966; }
    static double halfPiLo() { return 6.123233995736766e-17; }
    // pi, double-double
    static double piHi() { return 3.141592653589793; }
    static double piLo() { return 1.2246467991473532e-16; }
    // 2/pi, nearest double: the quadrant guess
    static double twoOverPi() { return 0.6366197723675814; }
    // pi/2 = part1 + part2 + part3 + part4
    static double halfPiPart1() { return 1.5707963267341256; }
    static double halfPiPart2() { return 6.077100506303966e-11; }
    static double halfPiPart3() { return 2.0222662487111665e-21; }
    static double halfPiPart4() { return 8.4784276603689e-32; }
    // ln 2 = ln2Hi + ln2Lo, ln2Hi of 42 bits: e * ln2Hi is exact
    static double ln2Hi() { return 0.6931471805598903; }
    static double ln2Lo() { return 5.497923018708371e-14; }
    // ln 2 / 64 = hi + lo, hi of 36 bits: n * hi exact for |n| < 2^17
    static double ln2By64Hi() { return 0.010830424696223417; }
    static double ln2By64Lo() { return 2.572804622327669e-14; }
    // 64 / ln 2, nearest double
    static double sixtyFourByLn2() { return 92.33248261689366; }
    // 1 / ln 10, double-double
    static double invLn10Hi() { return 0.4342944819032518; }
    static double invLn10Lo() { return 1.098319650216765e-17; }
};

}  // namespace rts6x

#endif
