// Spec: ISO C 7.12.4.6 (sin and its neighbours for every finite argument): the first 1216 bits of
// 2/pi after the binary point, 32 to a word, most significant first. Generated by tools/math-tables.py; do not edit.

#include "ArgumentReduction.h"

namespace rts6x {

const unsigned ArgumentReduction::twoOverPi_[38] = {
    0xA2F9836Eu, 0x4E441529u, 0xFC2757D1u, 0xF534DDC0u,
    0xDB629599u, 0x3C439041u, 0xFE5163ABu, 0xDEBBC561u,
    0xB7246E3Au, 0x424DD2E0u, 0x06492EEAu, 0x09D1921Cu,
    0xFE1DEB1Cu, 0xB129A73Eu, 0xE88235F5u, 0x2EBB4484u,
    0xE99C7026u, 0xB45F7E41u, 0x3991D639u, 0x835339F4u,
    0x9C845F8Bu, 0xBDF9283Bu, 0x1FF897FFu, 0xDE05980Fu,
    0xEF2F118Bu, 0x5A0A6D1Fu, 0x6D367ECFu, 0x27CB09B7u,
    0x4F463F66u, 0x9E5FEA2Du, 0x7527BAC7u, 0xEBE5F17Bu,
    0x3D0739F7u, 0x8A5292EAu, 0x6BFB5FB1u, 0x1F8D5D08u,
    0x56033046u, 0xFC7B6BABu,
};

}  // namespace rts6x
