#!/usr/bin/env python3
# Spec: none - writes the constants and tables of src/math from first principles: pi by Machin's
# formula, ln 2 by the atanh series, and every other value by its Taylor series, all in Python
# integers as fixed point; each double the nearest one, each pair (hi, lo) a double-double.
import os
from fractions import Fraction

BITS = 700                      # fixed point: value * 2^BITS
ONE = 1 << BITS
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'src', 'math')


def atan_inv(n, bits):
    """atan(1/n) * 2^bits, by the alternating series."""
    one = 1 << (bits + 16)
    term = one // n
    total, k, sign = 0, 1, 1
    while term:
        total += sign * (term // k)
        term //= n * n
        k += 2
        sign = -sign
    return total >> 16


def pi_fixed(bits):
    # Machin: pi/4 = 4 atan(1/5) - atan(1/239)
    return 4 * (4 * atan_inv(5, bits + 8) - atan_inv(239, bits + 8)) >> 8


def atanh_fixed(num, den, bits):
    """atanh(num/den) * 2^bits, |num/den| <= 1/3; odd, so the sign is taken out first."""
    if num < 0:
        return -atanh_fixed(-num, den, bits)
    one = 1 << (bits + 16)
    term = one * num // den
    q = Fraction(num, den) ** 2
    total, k = 0, 1
    while term:
        total += term // k
        term = term * q.numerator // q.denominator
        k += 2
    return total >> 16


def exp_fixed(x):
    """e^x * ONE for x = fixed-point value (|x| small)."""
    total, term, k = 0, ONE, 0
    while term:
        total += term
        k += 1
        term = term * x // ONE // k
    return total


def ln_rational(v):
    """ln(v) * ONE for a positive Fraction v, as 2 atanh((v-1)/(v+1)) after taking out powers of 2."""
    e = 0
    while v > Fraction(4, 3):
        v /= 2
        e += 1
    while v < Fraction(2, 3):
        v *= 2
        e -= 1
    a = (v - 1) / (v + 1)
    return 2 * atanh_fixed(a.numerator, a.denominator, BITS) + e * LN2


def sin_cos_fixed(x):
    """(sin x, cos x) * ONE for fixed-point x, |x| < 1."""
    s, c = 0, 0
    term, k = ONE, 0                  # x^k / k!
    while term:
        if k % 4 == 0:
            c += term
        elif k % 4 == 1:
            s += term
        elif k % 4 == 2:
            c -= term
        else:
            s -= term
        k += 1
        term = term * x // ONE // k
    return s, c


def isqrt_fixed(x):
    import math
    return math.isqrt(x * ONE)


def atan_fixed(x):
    """atan(x) * ONE, 0 <= x <= 1: halve the angle once, then the series."""
    y = x * ONE // (ONE + isqrt_fixed(ONE + x * x // ONE))
    total, term, k, y2 = 0, y, 1, y * y // ONE
    sign = 1
    while term:
        total += sign * (term // k)
        term = term * y2 // ONE
        k += 2
        sign = -sign
    return 2 * total


PI = pi_fixed(BITS)
LN2 = 2 * atanh_fixed(1, 3, BITS)


def fx(v):
    return Fraction(v, ONE)


def dd(v):
    """A Fraction to (hi, lo), each the nearest double."""
    hi = float(v)
    lo = float(v - Fraction(hi))
    return hi, lo


def truncated(v, bits):
    """v rounded toward zero to `bits` significant bits, as an exact double."""
    v = Fraction(v)
    e = 0
    a = abs(v)
    while a >= 1:
        a /= 2
        e += 1
    while a < Fraction(1, 2):
        a *= 2
        e -= 1
    m = int(a * (1 << bits))
    r = Fraction(m, 1 << bits) * Fraction(2) ** e
    return float(r if v > 0 else -r)


def lit(x):
    r = repr(float(x))
    if 'e' not in r and '.' not in r and 'inf' not in r:
        r += '.0'
    return r


def write(name, text):
    with open(os.path.join(OUT, name), 'w') as f:
        f.write(text)


def table(cls, member, values):
    rows = []
    for i in range(0, len(values), 3):
        rows.append('    ' + ', '.join(lit(v) for v in values[i:i + 3]) + ',')
    return 'const double %s::%s[%d] = {\n%s\n};\n' % (cls, member, len(values), '\n'.join(rows))


GEN = 'Generated by tools/math-tables.py; do not edit.'

# ---- scalar constants -------------------------------------------------------------------------
pi = fx(PI)
ln2 = fx(LN2)
ln10 = fx(ln_rational(Fraction(10)))
consts = []


def const(name, value, note):
    consts.append((name, lit(value), note))


halfpi = pi / 2
const('halfPiHi', dd(halfpi)[0], 'pi/2, double-double')
const('halfPiLo', dd(halfpi)[1], '')
const('piHi', dd(pi)[0], 'pi, double-double')
const('piLo', dd(pi)[1], '')
const('twoOverPi', float(2 / pi), '2/pi, nearest double: the quadrant guess')
# pi/2 in four parts, the first three of 33 bits so a k below 2^20 times each is exact.
rest = halfpi
parts = []
for i in range(3):
    p = truncated(rest, 33)
    parts.append(p)
    rest -= Fraction(p)
parts.append(float(rest))
for i, p in enumerate(parts):
    const('halfPiPart%d' % (i + 1), p, 'pi/2 = part1 + part2 + part3 + part4' if i == 0 else '')
for i, p in enumerate(parts):
    const('piBy256Part%d' % (i + 1), p / 128, 'pi/256 = the four parts of pi/2 over 128, exactly' if i == 0 else '')
const('twoFiftySixByPi', float(256 / pi), '256/pi, nearest double: the sine table index guess')
const('ln2Hi', truncated(ln2, 42), 'ln 2 = ln2Hi + ln2Lo, ln2Hi of 42 bits: e * ln2Hi is exact')
const('ln2Lo', float(ln2 - Fraction(truncated(ln2, 42))), '')
c1 = truncated(ln2 / 64, 36)
const('ln2By64Hi', c1, 'ln 2 / 64 = hi + lo, hi of 36 bits: n * hi exact for |n| < 2^17')
const('ln2By64Lo', float(ln2 / 64 - Fraction(c1)), '')
const('sixtyFourByLn2', float(64 / ln2), '64 / ln 2, nearest double')
c1 = truncated(ln2 / 128, 35)
const('ln2By128Hi', c1, 'ln 2 / 128 = hi + lo, hi of 35 bits: n * hi exact for |n| < 2^18')
const('ln2By128Lo', float(ln2 / 128 - Fraction(c1)), '')
const('oneTwentyEightByLn2', float(128 / ln2), '128 / ln 2, nearest double')
inv10 = 1 / ln10
const('invLn10Hi', dd(inv10)[0], '1 / ln 10, double-double')
const('invLn10Lo', dd(inv10)[1], '')

lines, defs = [], []
for name, value, note in consts:
    if note:
        lines.append('    // %s' % note)
    lines.append('    static const double %s;' % name)
    defs.append('const double MathConstants::%s = %s;' % (name, value))
write('MathConstants.h', '''// Spec: ISO C 7.12 (the constants its functions are built on), IEEE 754 binary64. %s
// pi from Machin's formula, ln 2 and ln 10 from the atanh series, in integers to 700 bits; each
// value the nearest double, or a sum of doubles where one is not enough.
#ifndef RTS6X_MATH_CONSTANTS_H
#define RTS6X_MATH_CONSTANTS_H

namespace rts6x {

// Data members rather than inline functions: cpp11 loads one where it is named in an expression,
// where an inline call there costs a push and a pop of everything evaluated before it.
class MathConstants {
public:
%s
};

}  // namespace rts6x

#endif
''' % (GEN, '\n'.join(lines)))
write('MathConstants.cpp', '''// Spec: ISO C 7.12 (the constants its functions are built on), IEEE 754 binary64: the values
// MathConstants.h declares. %s

#include "MathConstants.h"

namespace rts6x {

%s

}  // namespace rts6x
''' % (GEN, '\n'.join(defs)))

# ---- 2^(j/64), j = 0..63 ----------------------------------------------------------------------
hi, lo = [], []
for j in range(128):
    v = fx(exp_fixed(LN2 * j // 128))
    h = truncated(v, 26)
    hi.append(h)
    lo.append(float(v - Fraction(h)))
write('ExpTable.cpp', '''// Spec: ISO C 7.12.6.1 (exp): 2^(j/128) for j = 0..127 as top + rest, the top of 26 bits (so its
// product with a 26-bit number is exact), the rest the nearest double to what is left. %s

#include "ExpKernel.h"

namespace rts6x {

%s
%s
}  // namespace rts6x
''' % (GEN, table('ExpKernel', 'powerTop_', hi), table('ExpKernel', 'powerRest_', lo)))

# ---- log: r_j the nearest double to 1/(1 + j/128); -ln r_j as a double-double ---------------
recip, lhi, llo = [], [], []
for j in range(128):
    r = Fraction(round(Fraction(256 * 128, 128 + j)), 256)
    recip.append(float(r))
    v = -fx(ln_rational(r))
    h = Fraction(int(v * 2 ** 42), 2 ** 42)
    lhi.append(float(h))
    llo.append(float(v - h))
write('LogTable.cpp', '''// Spec: ISO C 7.12.6.7 (log): r_j, 1/(1 + j/128) rounded to 8 bits (so m r_j - 1 is exact from
// two products), and -ln r_j as hi + lo, hi a multiple of 2^-42 (so e ln2Hi + hi is exact), for
// j = 0..127. %s

#include "Logarithm.h"

namespace rts6x {

%s
%s
%s
}  // namespace rts6x
''' % (GEN, table('Logarithm', 'reciprocal_', recip), table('Logarithm', 'logHi_', lhi),
       table('Logarithm', 'logLo_', llo)))

# ---- sin and cos of j/64, j = 0..52 -----------------------------------------------------------
shi, slo, chi, clo = [], [], [], []
for j in range(53):
    s, c = sin_cos_fixed(ONE * j // 64)
    a, b = dd(fx(s))
    shi.append(a)
    slo.append(b)
    a, b = dd(fx(c))
    chi.append(a)
    clo.append(b)
rows = []
for j in range(128):
    s, c = sin_cos_fixed(PI * j // 256)
    for v in (fx(s), fx(c)):
        t = truncated(v, 26) if v else 0.0
        rows += [t, float(v - Fraction(t))]
write('SinCosTable.cpp', '''// Spec: ISO C 7.12.4.6, 7.12.4.5 (sin, cos): sin(j/64) and cos(j/64) for j = 0..52, which
// covers |r| <= pi/4, as double-doubles; and of j pi/256 for j = 0..127 in rows of four, sin and
// cos, each a top of 26 bits (exact times another 26 bits) and the nearest double to the rest. %s

#include "Trigonometric.h"

namespace rts6x {

%s
%s
%s
%s
%s
}  // namespace rts6x
''' % (GEN, table('Trigonometric', 'sinHi_', shi), table('Trigonometric', 'sinLo_', slo),
       table('Trigonometric', 'cosHi_', chi), table('Trigonometric', 'cosLo_', clo),
       table('Trigonometric', 'rows_', rows)))

# ---- atan(j/16), j = 0..16 --------------------------------------------------------------------
ahi, alo = [], []
for j in range(17):
    h, l = dd(fx(atan_fixed(ONE * j // 16)))
    ahi.append(h)
    alo.append(l)
bhi, blo = [], []
for j in range(33):
    h, l = dd(fx(atan_fixed(ONE * j // 32)))
    bhi.append(h)
    blo.append(l)
write('AtanTable.cpp', '''// Spec: ISO C 7.12.4.3, 7.12.4.4 (atan, atan2): atan(j/16) for j = 0..16 and atan(j/32) for
// j = 0..32, as double-doubles. %s

#include "ArcTangent.h"

namespace rts6x {

%s
%s
%s
%s
}  // namespace rts6x
''' % (GEN, table('ArcTangent', 'atanHi_', ahi), table('ArcTangent', 'atanLo_', alo),
       table('ArcTangent', 'atan32Hi_', bhi), table('ArcTangent', 'atan32Lo_', blo)))

# ---- 1/sqrt(m) on 64 bins of [1, 4): a line through two Chebyshev nodes of each ------------
import math


def rsqrt(v):
    """1/sqrt(v) for a positive Fraction v, to 700 bits."""
    return Fraction(ONE, math.isqrt(int(v * ONE * ONE)))


base, slope = [], []
for i in range(64):
    lo = Fraction(1 + i // 32) * (1 + Fraction(i % 32, 32))
    width = Fraction(1 + i // 32, 32)
    mid = lo + width / 2
    d = width / 2 * Fraction(7071067811865476, 10 ** 16)
    n1, n2 = mid - d, mid + d
    k = (rsqrt(n2) - rsqrt(n1)) / (n2 - n1)
    slope.append(float(k))
    base.append(float(rsqrt(n1) - k * n1))
write('SqrtTable.cpp', '''// Spec: ISO C 7.12.7.5 (sqrt): the first guess at 1/sqrt(m), m in [1, 4) in 64 bins (m's last
// exponent bit and five fraction bits), as base + slope * m, within 2^-13 of the true value. %s

#include "SquareRoot.h"

namespace rts6x {

%s
%s
}  // namespace rts6x
''' % (GEN, table('SquareRoot', 'base_', base), table('SquareRoot', 'slope_', slope)))

# ---- 1/m on 128 bins of [1, 2): the value at each bin's middle, within 2^-8 ------------------
seeds = [float(Fraction(256, 257 + 2 * i)) for i in range(128)]
write('ReciprocalTable.cpp', '''// Spec: IEEE 754 binary64: the first guess for Newton's method on 1/m, m in [1, 2) in 128 bins
// by its top seven fraction bits - 1/m at each bin's middle, within 2^-8 of 1/m. %s

#include "NewtonIteration.h"

namespace rts6x {

%s
}  // namespace rts6x
''' % (GEN, table('NewtonIteration', 'seed_', seeds)))

# ---- 2/pi to 1216 bits, 38 words, most significant first ----------------------------------
P = 1216
pib = pi_fixed(P + 200)
B = (1 << (P + 1 + P + 200)) // pib          # floor(2^P * 2/pi)
words = [(B >> (32 * (37 - i))) & 0xFFFFFFFF for i in range(38)]
rows = []
for i in range(0, 38, 4):
    rows.append('    ' + ', '.join('0x%08Xu' % w for w in words[i:i + 4]) + ',')
write('TwoOverPiBits.cpp', '''// Spec: ISO C 7.12.4.6 (sin and its neighbours for every finite argument): the first 1216 bits of
// 2/pi after the binary point, 32 to a word, most significant first. %s

#include "ArgumentReduction.h"

namespace rts6x {

const unsigned ArgumentReduction::twoOverPi_[38] = {
%s
};

}  // namespace rts6x
''' % (GEN, '\n'.join(rows)))
print('math-tables: wrote MathConstants.h, MathConstants.cpp, ExpTable.cpp, LogTable.cpp, SinCosTable.cpp, AtanTable.cpp, SqrtTable.cpp, ReciprocalTable.cpp, TwoOverPiBits.cpp')
