#!/usr/bin/env python3
# Spec: none - writes probe.s: rts6x_probe(helper, x, y, out) fills every register but B15 with
# 0xA5000000 + its number, calls the helper with x in A4 and y in B4, and stores all 64 registers
# to out[] afterwards (out[i] for Ai, out[32 + i] for Bi), so a test can see what the call changed.
regs = ["A%d" % i for i in range(32)] + ["B%d" % i for i in range(32)]
saved = ["A10", "A11", "A12", "A13", "A14", "A15", "B10", "B11", "B12", "B13", "B14", "B3"]
FRAME = 4 * (len(saved) + 4 + 64 + 2)
ARGS = len(saved) + 1          # word index of the four arguments
DUMP = ARGS + 4                # word index of the 64-word dump
L = []
o = L.append
o("; Spec: none - generated by gen-probe.py: the register probe for the helpers' Table 8-9 test.")
o("\t.global\trts6x_probe")
o("\t.text")
o("rts6x_probe:")
o("\tADDK\t-%d, B15" % FRAME)
for k, r in enumerate(saved): o("\tSTW\t%s, *+B15[%d]" % (r, 1 + k))
for k, r in enumerate(["A4", "B4", "A6", "B6"]): o("\tSTW\t%s, *+B15[%d]" % (r, ARGS + k))
for i, r in enumerate(regs):
    if r == "B15": continue
    v = 0xA5000000 + i
    o("\tMVKL\t0x%08x, %s" % (v, r)); o("\tMVKH\t0x%08x, %s" % (v, r))
o("\tLDW\t*+B15[%d], B31" % ARGS)
o("\tLDW\t*+B15[%d], A4" % (ARGS + 1))
o("\tLDW\t*+B15[%d], B4" % (ARGS + 2))
o("\tNOP\t4")
o("\tMVKL\tprobe_back, B3"); o("\tMVKH\tprobe_back, B3")
o("\tB\tB31"); o("\tNOP\t5")
o("probe_back:")
for i, r in enumerate(regs):
    if r == "B15": continue
    o("\tSTW\t%s, *+B15[%d]" % (r, DUMP + i))
o("\tLDW\t*+B15[%d], A0" % (ARGS + 3)); o("\tNOP\t4")
for i in range(64):
    o("\tLDW\t*+B15[%d], A1" % (DUMP + i)); o("\tNOP\t4"); o("\tSTW\tA1, *A0++")
for k, r in enumerate(saved): o("\tLDW\t*+B15[%d], %s" % (1 + k, r))
o("\tNOP\t4")
o("\tADDK\t%d, B15" % FRAME)
o("\tB\tB3"); o("\tNOP\t5")
open(__file__.replace("gen-probe.py", "probe.s"), "w").write("\n".join(L) + "\n")
